/**
 * Type definitions for projector-app WebSocket authentication
 * Feature: 001-projector-auth
 *
 * These types define the authentication entities for server-generated custom tokens
 * and projector-specific WebSocket sessions.
 */

/**
 * Connection state for projector-app UI
 */
export type ConnectionState = 'disconnected' | 'authenticating' | 'connected' | 'error';

/**
 * Server-generated custom token for projector authentication
 * Generated by api-server /api/projector/auth-token endpoint
 */
export interface ProjectorAuthToken {
  /** Firebase custom token (JWT) */
  token: string;
  /** Unix timestamp when token expires (token valid for 1 hour) */
  expiresAt: number;
  /** Unique identifier for this projector instance (format: projector-{uuid}) */
  uid: string;
}

/**
 * Active WebSocket connection session for a projector instance
 * Managed by socket-server /projector-socket namespace
 */
export interface ProjectorSession {
  /** Socket.IO socket.id */
  sessionId: string;
  /** Firebase UID from token claims */
  uid: string;
  /** Verified role from token custom claims (always 'projector') */
  role: 'projector';
  /** Unix timestamp of connection */
  connectedAt: number;
  /** Last activity timestamp */
  lastHeartbeat: number;
  /** Additional connection metadata */
  metadata: ProjectorMetadata;
}

/**
 * Metadata for projector connection
 */
export interface ProjectorMetadata {
  /** Optional venue identifier */
  venueId?: string;
  /** Display purpose (primary display, backup, DJ screen, etc.) */
  displayType?: 'primary' | 'backup' | 'dj';
  /** Browser/device info */
  userAgent: string;
  /** Connection origin (for audit) */
  ipAddress: string;
}

/**
 * UI state for displaying connection status to venue staff
 */
export interface ConnectionStatus {
  /** Current connection state */
  state: ConnectionState;
  /** User-friendly status message */
  message: string;
  /** Timestamp of last successful connection */
  lastConnected?: number;
  /** Error message if state === 'error' */
  errorDetails?: string;
  /** Current retry attempt (1-10) during reconnection */
  retryAttempt?: number;
  /** Milliseconds until next retry */
  nextRetryIn?: number;
}

/**
 * Request payload for custom token generation
 * Sent to POST /api/projector/auth-token
 */
export interface TokenGenerationRequest {
  // No body required - authentication via X-API-Key header
}

/**
 * Response from custom token generation endpoint
 */
export interface TokenGenerationResponse {
  /** Firebase custom token */
  token: string;
  /** Expiration timestamp */
  expiresAt: number;
  /** Generated UID for this projector */
  uid: string;
}

/**
 * Error response from token generation endpoint
 */
export interface TokenGenerationError {
  /** Error code */
  error: string;
  /** Human-readable message */
  message: string;
  /** HTTP status code */
  statusCode: number;
}

/**
 * WebSocket authentication event payloads
 * NOTE: Auth payload types are defined in SocketEvents.ts to avoid duplication
 * Import from there: AuthRequiredPayload, AuthenticatePayload, AuthenticatedPayload, AuthFailedPayload
 */

/**
 * Audit log entry for authentication attempts (FR-007)
 */
export interface AuthenticationAttemptLog {
  /** Unix timestamp */
  timestamp: number;
  /** Projector UID */
  uid: string;
  /** Event type */
  event: 'TOKEN_REQUESTED' | 'TOKEN_GENERATED' | 'AUTH_SUCCESS' | 'AUTH_FAILED';
  /** Outcome */
  outcome: 'success' | 'failure';
  /** Source IP */
  ipAddress: string;
  /** Browser info */
  userAgent: string;
  /** Error code if outcome === 'failure' */
  errorCode?: string;
  /** Human-readable error */
  errorMessage?: string;
  /** Additional context */
  metadata?: Record<string, any>;
}
